package(default_visibility = ["//visibility:public"])

py_library(
    name = "af",
    srcs = ["af.py"]
    )

py_library(
    name = "am",
    srcs = ["am.py"]
    )

py_library(
    name = "bm_latn",
    srcs = ["bm_latn.py"]
    )

py_library(
    name = "ha",
    srcs = ["ha.py"]
    )

py_library(
    name = "ig",
    srcs = ["ig.py"]
    )

py_library(
    name = "mg",
    srcs = ["mg.py"]
    )

py_library(
    name = "so",
    srcs = ["so.py"]
    )

py_library(
    name = "sw",
    srcs = ["sw.py"]
    )

py_library(
    name = "wo",
    srcs = ["wo.py"]
    )

py_library(
    name = "yo",
    srcs = ["yo.py"]
    )

py_library(
    name = "zu",
    srcs = ["zu.py"]
    )

py_library(
    name = "utils",
    srcs = ["utils.py"]
    )
